# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{phoney}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jan Habermann"]
  s.date = %q{2010-02-13}
  s.description = %q{Ruby library that parses a phone number and automatically formats it correctly, depending on the country/locale you set.}
  s.email = %q{jan@habermann24.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "Rakefile",
     "lib/data/regions.yml",
     "lib/phoney.rb",
     "lib/phoney/base.rb",
     "lib/phoney/parser.rb",
     "lib/phoney/region.rb",
     "lib/phoney/utils.rb",
     "lib/phoney/version.rb",
     "phoney.gemspec",
     "spec/parser/de_spec.rb",
     "spec/parser/us_spec.rb",
     "spec/phone_number_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/habermann24/phoney}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby library that formats phone numbers.}
  s.test_files = [
    "spec/parser/de_spec.rb",
     "spec/parser/us_spec.rb",
     "spec/phone_number_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

