require File.join(File.dirname(__FILE__), 'phone_number', 'version')
require File.join(File.dirname(__FILE__), 'phone_number', 'utils')
require File.join(File.dirname(__FILE__), 'phone_number', 'region')
require File.join(File.dirname(__FILE__), 'phone_number', 'parser')
require File.join(File.dirname(__FILE__), 'phone_number', 'base')